### ISSUE TITLE
[Question] If we start a new Virto project is this the best way?

### ISSUE THREAD

**Issue by CKGrafico** [VirtoCommerce/vue-starter-theme#5]
Hello se are starting a new project with Virto and this seems the most relevant theme. We can manage with different Front technologies and we are happy with vue but we have to be sure that this is your recommendation before start.

Additional questions:
- Why MPA and not Nuxt?
- Do we have to modify the code of the template or we can extend the template (like wordpress themes for example)?
- Is vue 3 and hooks in your roadmap?
- We will probably need to do a lot of custom things in our app, is better to start from scratch communicating to the API from Virto or extend this template?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6910 has been created

**Comment by tatarincev** [comment]
Hi @CKGrafico, I'm glad that you consider this theme for your projects, and I'm happy to answer all of your questions: 

**Q**: _Why MPA and not NUXT?_ 
**A**: The main reason why we chose MPA is the ability to continue to use existing storefront functionality and have `mixed` mode to `inject` JS components into pages that are rendered on the server-side along which the many useful features that are difficult to reuse in other frameworks. Also, here are other things that influenced our decision: 
- Because of power ASP.NET Core (web security, Web API, routing, authentication and authorization, middleware, .NET and C#)
- Theming, theme resource inheritance, end-users templates Liquid, static content management, and WEB CMS elements
- Multi everything (store, currency, languages)
- SLUG routing 
- SSR for essential  for  SEO Liquid pages (sing in, reset password, product page, products browsing)
- Out the box Authentication/Authorization 
- [xAPI](https://github.com/VirtoCommerce/vc-module-experience-api)  (graphQL)  integration 

**Q**: _Do we have to modify the code of the template or we can extend the template (like wordpress themes for example)?_
**A**:  The starter theme is designed for do any customization via direct theme code changes, you can feel free to edit any theme resources within your solution.

**Q**: _Is vue 3 and hooks in your roadmap?_
**A**: Not in this year.

**Q**: _We will probably need to do a lot of custom things in our app, is better to start from scratch communicating to the API from Virto or extend this template?_
**A**:  To answer this question need to dive into your context in more detail. Anyway if you have plan to build eCommerce I the many eCommerce domain things can be reused and be taken from the existing theme.

I would like to recommend you to use these project branches for your new project: Keep in mind that these projects are under development.

**Recommended storefront version:**

[vue-starter-theme/dev](https://github.com/VirtoCommerce/vue-starter-theme/tree/dev) - The next generation of starter theme that located in `dev` branch. This version is absolutely different from the version in the `master`  that built with using  https://www.storefrontui.io/ semantic UI components and new [composition-API](https://v3.vuejs.org/guide/composition-api-introduction.html)  VueJS instead of vuex state management.
https://vst-storefront.develop.govirto.com/ - live theme demo


[Storefront 6.0 (beta)](https://github.com/VirtoCommerce/vc-storefront/tree/feature/x-api-integration) - The version of a storefront that fully adapted to work with [VirtoCommerce xAPI](https://github.com/VirtoCommerce/vc-module-experience-api) (graphQL)  and doesn't contains any eCommerce business logic and can be used as binary without direct code changes in the custom projects.

**Comment by CKGrafico** [comment]
Hello @tatarincev first thanks for your quick and super useful reply, I know that you have probably better things to do and you have used your time to reply all my questions.

**Q**: _Why MPA and not NUXT?_
Thanks, clarified and totally understood.

**Q**: _Do we have to modify the code of the template or we can extend the template (like wordpress themes for example)?_
Its clear, that means that there is not something like "child templates" I mean if you update the template will be difficult to update our theme or do you have the "child like system".

**Q**: _Is vue 3 and hooks in your roadmap?_
Ok, thanks 👍 

**Q**: _We will probably need to do a lot of custom things in our app, is better to start from scratch communicating to the API from Virto or extend this template?_
Its ok with all the info you have provided

> I would like to recommend you to use these project branches for your new project: Keep in mind that these projects are under development.
Amazing tip, thanks!!

**Comment by OlegoO** [comment]
https://www.virtocommerce.org/t/if-we-start-a-new-virto-project-is-this-the-best-way/294
